// Code generated by mockery v2.42.3. DO NOT EDIT.

package mocks

import (
	common "data-spaces-backend/domain/common"

	echo "github.com/labstack/echo/v4"

	mock "github.com/stretchr/testify/mock"

	traceability "data-spaces-backend/domain/model/traceability"
)

// IPartsStructureUsecase is an autogenerated mock type for the IPartsStructureUsecase type
type IPartsStructureUsecase struct {
	mock.Mock
}

// GetPartsStructure provides a mock function with given fields: c, getPartsStructureModel
func (_m *IPartsStructureUsecase) GetPartsStructure(c echo.Context, getPartsStructureModel traceability.GetPartsStructureInput) (traceability.PartsStructureModel, error) {
	ret := _m.Called(c, getPartsStructureModel)

	if len(ret) == 0 {
		panic("no return value specified for GetPartsStructure")
	}

	var r0 traceability.PartsStructureModel
	var r1 error
	if rf, ok := ret.Get(0).(func(echo.Context, traceability.GetPartsStructureInput) (traceability.PartsStructureModel, error)); ok {
		return rf(c, getPartsStructureModel)
	}
	if rf, ok := ret.Get(0).(func(echo.Context, traceability.GetPartsStructureInput) traceability.PartsStructureModel); ok {
		r0 = rf(c, getPartsStructureModel)
	} else {
		r0 = ret.Get(0).(traceability.PartsStructureModel)
	}

	if rf, ok := ret.Get(1).(func(echo.Context, traceability.GetPartsStructureInput) error); ok {
		r1 = rf(c, getPartsStructureModel)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PutPartsStructure provides a mock function with given fields: c, putpartsStructureInput
func (_m *IPartsStructureUsecase) PutPartsStructure(c echo.Context, putpartsStructureInput traceability.PutPartsStructureInput) (traceability.PartsStructureModel, common.ResponseHeaders, error) {
	ret := _m.Called(c, putpartsStructureInput)

	if len(ret) == 0 {
		panic("no return value specified for PutPartsStructure")
	}

	var r0 traceability.PartsStructureModel
	var r1 common.ResponseHeaders
	var r2 error
	if rf, ok := ret.Get(0).(func(echo.Context, traceability.PutPartsStructureInput) (traceability.PartsStructureModel, common.ResponseHeaders, error)); ok {
		return rf(c, putpartsStructureInput)
	}
	if rf, ok := ret.Get(0).(func(echo.Context, traceability.PutPartsStructureInput) traceability.PartsStructureModel); ok {
		r0 = rf(c, putpartsStructureInput)
	} else {
		r0 = ret.Get(0).(traceability.PartsStructureModel)
	}

	if rf, ok := ret.Get(1).(func(echo.Context, traceability.PutPartsStructureInput) common.ResponseHeaders); ok {
		r1 = rf(c, putpartsStructureInput)
	} else {
		r1 = ret.Get(1).(common.ResponseHeaders)
	}

	if rf, ok := ret.Get(2).(func(echo.Context, traceability.PutPartsStructureInput) error); ok {
		r2 = rf(c, putpartsStructureInput)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewIPartsStructureUsecase creates a new instance of IPartsStructureUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIPartsStructureUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *IPartsStructureUsecase {
	mock := &IPartsStructureUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
