// Code generated by mockery v2.27.1. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"

	traceability "data-spaces-backend/domain/model/traceability"
)

// IStatusUsecase is an autogenerated mock type for the IStatusUsecase type
type IStatusUsecase struct {
	mock.Mock
}

// GetStatus provides a mock function with given fields: c, getStatusModel
func (_m *IStatusUsecase) GetStatus(c echo.Context, getStatusModel traceability.GetStatusModel) ([]traceability.StatusModel, *string, error) {
	ret := _m.Called(c, getStatusModel)

	var r0 []traceability.StatusModel
	var r1 *string
	var r2 error
	if rf, ok := ret.Get(0).(func(echo.Context, traceability.GetStatusModel) ([]traceability.StatusModel, *string, error)); ok {
		return rf(c, getStatusModel)
	}
	if rf, ok := ret.Get(0).(func(echo.Context, traceability.GetStatusModel) []traceability.StatusModel); ok {
		r0 = rf(c, getStatusModel)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]traceability.StatusModel)
		}
	}

	if rf, ok := ret.Get(1).(func(echo.Context, traceability.GetStatusModel) *string); ok {
		r1 = rf(c, getStatusModel)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*string)
		}
	}

	if rf, ok := ret.Get(2).(func(echo.Context, traceability.GetStatusModel) error); ok {
		r2 = rf(c, getStatusModel)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// PutStatusCancel provides a mock function with given fields: c, statusModel
func (_m *IStatusUsecase) PutStatusCancel(c echo.Context, statusModel traceability.StatusModel) error {
	ret := _m.Called(c, statusModel)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context, traceability.StatusModel) error); ok {
		r0 = rf(c, statusModel)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PutStatusReject provides a mock function with given fields: c, statusModel
func (_m *IStatusUsecase) PutStatusReject(c echo.Context, statusModel traceability.StatusModel) error {
	ret := _m.Called(c, statusModel)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context, traceability.StatusModel) error); ok {
		r0 = rf(c, statusModel)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewIStatusUsecase interface {
	mock.TestingT
	Cleanup(func())
}

// NewIStatusUsecase creates a new instance of IStatusUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIStatusUsecase(t mockConstructorTestingTNewIStatusUsecase) *IStatusUsecase {
	mock := &IStatusUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
