@startuml "trade_negotiation_state_machine"
hide empty description

state CREATE_PARTSSTRUCTUREARTS: CONSUMER
state REQUEST_TRADE: CONSUMER
state RESPONSE_TRADE: PROVIDER
state SET_CFP: PROVIDER
state COMPLETED_CFPRESPONSESTATUS
state ALLOWED_CFP: PROVIDER
state GET_CFP : CONSUMER

[*] --> CREATE_PARTSSTRUCTUREARTS: 6.PutPartsStructure
CREATE_PARTSSTRUCTUREARTS -->  REQUEST_TRADE: 7.PutTradeRequest
REQUEST_TRADE -->  RESPONSE_TRADE: 13.PutTradeResponse

[*] --> SET_CFP: 15.PutCfp
SET_CFP -->  COMPLETED_CFPRESPONSESTATUS
COMPLETED_CFPRESPONSESTATUS -->  ALLOWED_CFP: allowed cfp

ALLOWED_CFP --> GET_CFP: 14.GetCfp
RESPONSE_TRADE --> GET_CFP: 14.GetCfp

GET_CFP -->[*]
@enduml